### ISSUE TITLE
[proposal] Extract code point retrieval logic into a separate function

### ISSUE THREAD

**Issue by miclf** [backflip/gulp-iconfont-css#12]
(I’m using the `.scss` template to give examples. I don’t if it’s technically possible to do the same with Less)

The correct code point associated to an icon file name is currently determined by a series of `@if` instructions generated inside the `icon` mixin, as shown below.

``` scss
@mixin icon($filename) {
    $char: "";
<% _.each(glyphs, function(glyph) { %>
    @if $filename == <%= glyph.fileName %> {
        $char: "\<%= glyph.codePoint %>";
    }<% }); %>

    &:before {
        @extend %icon;
        content: $char;
    }
}
```

However, in some cases, it would be useful to be able to get the code point of a given icon in order to use it for other purposes outside of this mixin.

For example, I have a use case where I would like to use an icon in an `:after` pseudo-element.

``` scss
.some-button:after {
    @include icon('unicorn');
}
```

This doesn’t work. Calling the mixin produces an error, because it inserts a `:before` pseudo-element inside the `:after` selector.

I suggest extracting the series of `@if`to their own function, with the unique goal of returning the code point associated to an icon name. It would make this logic reusable and allow this kind of syntax:

``` scss
.some-button:after {
    content: icon-char('unicorn');
}
```

The function would look like that:

``` scss
@function icon-char($filename) {
    $char: "";

    @if $filename == unicorn {
        $char: "\E001";
    }
    @if $filename == cat {
        $char: "\E002";
    }
    /* other @if instructions */

    @return $char;
}
```

and the `icon` mixin itself could be simplified to

``` scss
@mixin icon($filename) {
    &:before {
        @extend %icon;
        content: icon-char($filename);
    }
}
```

What do you think?
