### ISSUE TITLE
Issue in mixin icon: can't extend %icon

### ISSUE THREAD

**Issue by alkaithil** [backflip/gulp-iconfont-css#33]
I'm having trouble displaying my icons and I believe it's because the mixin `icon-styles` is not being properly included inside the `icon` mixin. 

```scss
@mixin icon($filename, $insert: before, $extend: true) {
	&:#{$insert} {
		@if $extend {
			@extend %icon;
		} @else {
			@include icon-styles;
		}
		content: icon-char($filename);
	}
}
```
If I remove the if/else state and try to `@extend %icon` directly, it's not working either. However, if I ìnclude `@icon-styles` directly, it works.

What might be causing this behaviour? Am I missing something?
