### ISSUE TITLE
removing the code of the icons from the class

### ISSUE THREAD

**Issue by slzr** [backflip/gulp-iconfont-css#37]
how i can remove the code of the icons in the class?
from this:
```css
.icon-uEA01-docs:before {
	content: "\E001";
}
```
to this:
```css
.icon-docs:before {
	content: "\E001";
}
```
